---
- name: Make sure apt-get is up to date
  apt: update_cache=yes
- name: Upgrade Packages
  apt: upgrade=dist
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      state=started
      delay=30
      timeout=300
  sudo: false

- user: name=postgres shell=/bin/bash groups=sudo append=yes
- name: create file for postgres repo
  file: path="/etc/apt/sources.list.d/postgresql.list" state=touch
- name: add postgres repo to file
  lineinfile: line="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main 9.5" dest="/etc/apt/sources.list.d/postgresql.list" state=present
- name: Get apt-key for psql version 9.5
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
- apt: update_cache=yes
- apt: name={{item}} state=present
  with_items:
    - postgresql-client-9.5
    - postgresql-common
    - postgresql-9.5
    - vim
    - python
    - python-dev
    - libpq-dev
    - gcc
    - npm
- apt: upgrade=dist
- name: install pip
  easy_install: name=pip 


- name: check if copy (below) has already been performed pg_hba
  stat: path=/etc/postgresql/9.5/main/pg_hba.conf.bak
  register: pg_hba_check
- name: rename default config files FIGURE OUT HOW TO DO THIS CORRECTLY
  command: cp /etc/postgresql/9.5/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf.bak
  when: pg_hba_check.stat.exists == False

- name: check if copy (below) has already been performed for postgresql
  stat: path=/etc/postgresql/9.5/main/postgresql.conf.bak
  register: postgresql_check
- name: rename default config files FIGURE OUT HOW TO DO THIS CORRECTLY
  command: cp /etc/postgresql/9.5/main/postgresql.conf /etc/postgresql/9.5/main/postgresql.conf.bak
  when: postgresql_check.stat.exists == False

- name: delete default config files
  file: path=/etc/postgresql/9.5/main/{{item}} state=absent
  with_items:
    - pg_hba.conf
    - postgresql.conf
- name: copy over configs for postgres
  copy: src={{item}} dest=/etc/postgresql/9.5/main/{{item}}.bak
  with_items: 
    - pg_hba.conf
    - postgresql.conf
- service: name=postgresql state=restarted
- name: create redis and symdash directories
  file: path="/etc/{{item}}" state=directory
  with_items:
    - redis
    - symdash
- name: copy over redis config
  copy: src=redis.conf dest=/etc/redis/redis.conf 
- name: install redis (add a when clause so this doesnt happen every time)
  get_url: url=http://download.redis.io/releases/redis-3.0.6.tar.gz dest=/etc/redis/redis-3.0.6.tar.gz
- unarchive: copy=no src=/etc/redis/redis-3.0.6.tar.gz dest=/etc/redis
- make: chdir=/etc/redis/redis-3.0.6
- command: ls /etc/redis/redis-3.0.6/src
  register: executables
- name: move redis executables
  command: cp /etc/redis/redis-3.0.6/src/{{item}} /etc/redis
  when: executables.stdout.find({{item}}) != -1
  with_items:
    - redis-cli
    - redis-server
- command: echo 'REDIS_HOME="/etc/redis"' >> /etc/environment
- file: path=/etc/redis/redis-3.0.6.tar.gz state=absent

